#pragma once
#include "../pch.hpp"

#define IOCTL_KILL_PROCESS CTL_CODE(FILE_DEVICE_UNKNOWN, 0x800, METHOD_BUFFERED, FILE_ANY_ACCESS)

EXTERN_C_START
NTSTATUS Comm_InitDefaultQueue(WDFDEVICE dev);
VOID Comm_EvtIoDeviceControl(WDFQUEUE, WDFREQUEST, size_t, size_t, ULONG);
VOID Comm_EvtIoStop(WDFQUEUE, WDFREQUEST, ULONG);
EXTERN_C_END
