#pragma once
#include "../pch.hpp"

#define IOCTL_KILL_PROCESS \
  CTL_CODE(FILE_DEVICE_UNKNOWN, 0x800, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_REGISTER_PROCESS_NOTIFY \
  CTL_CODE(FILE_DEVICE_UNKNOWN, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_UNREGISTER_PROCESS_NOTIFY \
  CTL_CODE(FILE_DEVICE_UNKNOWN, 0x802, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_WAIT_FOR_PROCESS_START \
  CTL_CODE(FILE_DEVICE_UNKNOWN, 0x803, METHOD_BUFFERED, FILE_ANY_ACCESS)

EXTERN_C_START
NTSTATUS Comm_InitDefaultQueue(WDFDEVICE dev);
VOID Comm_EvtIoDeviceControl(WDFQUEUE, WDFREQUEST, size_t, size_t, ULONG);
VOID Comm_EvtIoStop(WDFQUEUE, WDFREQUEST, ULONG);
EXTERN_C_END
