#include <string>
#include <unordered_set>

namespace SqlRequstes {
const std::unordered_set<std::string> TABLES = {
    "EventId", "EventRecordId", "EventTime", "Provider", "Channel",
    "Computer", "UserSid", "Level", "Task", "Opcode", "Keywords",
    "Image", "ImageLoaded", "SourceImage", "TargetImage", "ProcessName",
    "ParentProcessName", "ParentImage", "ParentCommandLine",
    "CommandLine", "Commandline", "NewProcessName", "OriginalFilename",
    "Hashes", "Version",
    "IpAddress", "LocalAddresses", "LocalPorts", "LocalPort",
    "RemoteAddresses", "RemotePorts", "DestinationPort",
    "TransmittedServices",
    "SubjectUserName", "SubjectUserSid", "TargetUserName",
    "TargetUserSid", "OldTargetUserName", "NewTargetUserName",
    "TargetDomainName", "TargetServerName", "LogonProcess",
    "LogonProcessName", "LogonType",
    "AuthenticationPackageName", "SecurityPackageName",
    "TicketOptions", "TicketEncryptionType", "GrantedAccess",
    "ObjectServer", "ObjectType", "ObjectName", "ObjectDN",
    "ObjectGUID", "ObjectClass", "ObjectClas",
    "ObjectAccessMask", "AccessList", "AccessMask",
    "Properties", "PropertyName", "ModifiedProperties_NewValue",
    "Operation", "OperationType", "Action", "RegName", "RegValue",
    "RelativeTargetName", "TargetObject", "TargetInfo", "TargetSid",
    "ServiceName", "ServiceSid", "ServicePrincipalNames",
    "AllowedToDelegateTo",
    "AuditPolicyChanges", "SettingType", "SettingValue",
    "SettingValueString", "AttributeLDAPDisplayName", "AttributeValue",
    "Properties_Name",
    "ApplicationPath", "CallerProcessName", "ChannelName",
    "CommandLineParams", "Details", "DeviceDescription", "EventType",
    "EventXML_Address", "EventXML_Param3", "ForwardTo",
    "ForwardAsAttachmentTo", "Message", "ModifyingApplication",
    "Param1", "Param2", "Parameters", "Parameters_Name", "Pattern",
    "Payload", "PluginDllName", "Process", "Status", "STATE", "State",
    "TaskName", "UpdateName", "UserAccountControl", "WorkstationName",
    "_cmdshell", "action_id", "additional_information", "class_type",
    "connections", "domain_in_lowercase_xxx", "enabled", "localport",
    "object_name", "param1_lower", "pwszAutoConfigUrl", "pwszProxy",
    "pwszProxyBypass", "statement",
    // housekeeping is auto-filled; we generally do not insert InsertionTime
    "InsertionTime"};
const char *TABLES_CREATE = R"SQL(
CREATE TABLE IF NOT EXISTS Events (
    EventId            INTEGER NOT NULL,
    EventRecordId      INTEGER,
    EventTime          DATETIME NOT NULL,
    Provider           TEXT,
    Channel            TEXT,
    Computer           TEXT,
    UserSid            TEXT,
    Level              INTEGER,
    Task               INTEGER,
    Opcode             INTEGER,
    Keywords           TEXT,
    -- process / image metadata
    Image              TEXT,
    ImageLoaded        TEXT,
    SourceImage        TEXT,
    TargetImage        TEXT,
    ProcessName        TEXT,
    ParentProcessName  TEXT,
    ParentImage        TEXT,
    ParentCommandLine  TEXT,
    CommandLine        TEXT,
    Commandline        TEXT,          -- Sigma sometimes references either
    NewProcessName     TEXT,
    OriginalFilename   TEXT,
    Hashes             TEXT,
    Version            TEXT,
    -- network / IPC
    IpAddress          TEXT,
    LocalAddresses     TEXT,
    LocalPorts         TEXT,
    LocalPort          TEXT,
    RemoteAddresses    TEXT,
    RemotePorts        TEXT,
    DestinationPort    TEXT,
    TransmittedServices TEXT,
    -- authentication / logon
    SubjectUserName    TEXT,
    SubjectUserSid     TEXT,
    TargetUserName     TEXT,
    TargetUserSid      TEXT,
    OldTargetUserName  TEXT,
    NewTargetUserName  TEXT,
    TargetDomainName   TEXT,
    TargetServerName   TEXT,
    LogonProcess       TEXT,
    LogonProcessName   TEXT,
    LogonType          TEXT,
    AuthenticationPackageName TEXT,
    SecurityPackageName TEXT,
    TicketOptions      TEXT,
    TicketEncryptionType TEXT,
    GrantedAccess      TEXT,
    -- object / registry / service changes
    ObjectServer       TEXT,
    ObjectType         TEXT,
    ObjectName         TEXT,
    ObjectDN           TEXT,
    ObjectGUID         TEXT,
    ObjectClass        TEXT,
    ObjectClas         TEXT,          -- typo variant appears in rules
    ObjectAccessMask   TEXT,
    AccessList         TEXT,
    AccessMask         TEXT,
    Properties         TEXT,
    PropertyName       TEXT,
    ModifiedProperties_NewValue TEXT,
    Operation          TEXT,
    OperationType      TEXT,
    Action             TEXT,
    RegName            TEXT,
    RegValue           TEXT,
    RelativeTargetName TEXT,
    TargetObject       TEXT,
    TargetInfo         TEXT,
    TargetSid          TEXT,
    -- services / Kerberos / delegation
    ServiceName        TEXT,
    ServiceSid         TEXT,
    ServicePrincipalNames TEXT,
    AllowedToDelegateTo TEXT,
    -- TransmittedServices TEXT,   -- duplicate, commented out
    -- policy / config
    AuditPolicyChanges TEXT,
    SettingType        TEXT,
    SettingValue       TEXT,
    SettingValueString TEXT,
    AttributeLDAPDisplayName TEXT,
    AttributeValue     TEXT,
    Properties_Name    TEXT,
    -- misc sigma fields seen in rule set
    ApplicationPath    TEXT,
    CallerProcessName  TEXT,
    ChannelName        TEXT,
    CommandLineParams  TEXT,
    Details            TEXT,
    DeviceDescription  TEXT,
    EventType          TEXT,
    EventXML_Address   TEXT,
    EventXML_Param3    TEXT,
    ForwardTo          TEXT,
    ForwardAsAttachmentTo TEXT,
    Message            TEXT,
    ModifyingApplication TEXT,
    -- Operation          TEXT,      -- duplicate, commented out
    Param1             TEXT,
    Param2             TEXT,
    Parameters         TEXT,
    Parameters_Name    TEXT,
    Pattern            TEXT,
    Payload            TEXT,
    PluginDllName      TEXT,
    Process            TEXT,
    Status             TEXT,
    STATE              TEXT,
    State              TEXT,
    TaskName           TEXT,
    UpdateName         TEXT,
    UserAccountControl TEXT,
    WorkstationName    TEXT,
    _cmdshell          TEXT,
    action_id          TEXT,
    additional_information TEXT,
    class_type         TEXT,
    connections        TEXT,
    domain_in_lowercase_xxx TEXT,
    enabled            TEXT,
    localport          TEXT,
    object_name        TEXT,
    param1_lower       TEXT,
    pwszAutoConfigUrl  TEXT,
    pwszProxy          TEXT,
    pwszProxyBypass    TEXT,
    statement          TEXT,
    -- housekeeping
    InsertionTime      DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_events_time      ON Events(EventTime);
CREATE INDEX IF NOT EXISTS idx_events_ids       ON Events(EventId, EventRecordId);
CREATE INDEX IF NOT EXISTS idx_events_provider  ON Events(Provider);
)SQL";
} // namespace SqlRequstes
